### ISSUE TITLE
Change the way how bomb notification sends

### ISSUE THREAD

**Issue by NoPlagiarism** [MurkyYT/CSAuto#16]
**Problems with every-second bomb notifications sent:**
- Spam notifications is just too loud
   - Especially with Telegram
- Telegram bot can reach his limits with those notifications
- Android can become laggy because of this

**Solution:**
- Notify when bomb starts ticking (with given unix timestamp) and bomb being defuser or 
- Implement client-side Android bomb timer

**Comment by MurkyYT** [comment]
> Implement client-side Android bomb timer

Client side Android bomb timer is in the mobile app
There will be an update now which adds your request of
> Notify when bomb starts ticking (with given unix timestamp)

Only there will be a date and a time the bomb was planted
