### ISSUE TITLE
Clarification on CS2 Compatibility

### ISSUE THREAD

**Issue by GabrielRimar** [MurkyYT/CSAuto#32]
### What happened?

Hi there,

I recently came across this repository and noticed that the README primarily talks about CS
. However, with the recent release of CS2, I was wondering if this project is compatible with it. I've been working with some similar tools and wanted to ensure this one would work for CS2 as well before diving in.

Any guidance or clarification on this would be much appreciated. If it's not compatible yet, do you have plans to update it for CS2?

Thanks in advance!

Best regards,
[Your Name]

### Steps to reproduce

N/A

**Comment by NoPlagiarism** [comment]
**Yes, it supports CS2 and only CS2**

FAQ refers to v1.1.2 as the latest version with CS:GO support

**Comment by GabrielRimar** [comment]
can it work for cs:go?

**Comment by AyJee-Y** [comment]
As far as im aware, there is no CSGO anymore for it to support

**Comment by NoPlagiarism** [comment]
No, but you can download latest version for it


https://github.com/MurkyYT/CSAuto/releases/tag/1.1.2

**Comment by GabrielRimar** [comment]
Doesn't this count for cheating and does it take acount the TOS of cs2?

**Comment by AyJee-Y** [comment]
Btw, does it support linux?

**Comment by GabrielRimar** [comment]
@MurkyYT can u answer pls

**Comment by NoPlagiarism** [comment]
> Btw, does it support linux?

No, it does not natively atm. But I don't know if it will start with Wine/Proton or not

**Comment by AyJee-Y** [comment]
Ok, i think it will be great to add support for the linux operating system, have a good day

**Comment by NoPlagiarism** [comment]
> add support for the linux operating system

You can create separate issue for this
