### ISSUE TITLE
[FEAT/REQ] Adding support to linux

### ISSUE THREAD

**Issue by AyJee-Y** [MurkyYT/CSAuto#33]
### Is your feature request related to a problem? Please describe.

**Hello everyone**
As many of you know there are large community of cs2 that play on linux.
I believe it would be great for you to add support to linux

### Describe the solution you'd like

I havent thought of a solution - since i didnt check where and how you use winAPI in your project (or other technologies that will need to be replaced for linux)

### Describe alternatives you've considered

Again i cannot think of an alternative solution

**Comment by MurkyYT** [comment]
Irrelevant as of right-now
