### ISSUE TITLE
[REPO SUGGESTION] Enable discussions and/or create chat anywhere

### ISSUE THREAD

**Issue by NoPlagiarism** [MurkyYT/CSAuto#4]
- [GH Discussions](https://docs.github.com/en/discussions) are better for some questions I wanna ask, than issues 
- Chat.. Like anywhere, [Matrix](https://joinmatrix.org/) or [Gitter](https://gitter.im/), [Discord](https://discord.com/) or sth else

**Comment by NoPlagiarism** [comment]
Sorry for previous issue on VanSwitch

**Comment by MurkyYT** [comment]
Hello, thanks for the suggestion, i enabled discussions as you asked!
Have fun!

**Comment by MurkyYT** [comment]
Hello, thanks for the suggestion, i enabled discussions as you asked!
Have fun!
